---
- name: Enable NETCONF
  hosts: junos
  roles:
    - Juniper.junos
  tasks:
    - name: Enable NETCONF
#      include_vars: group_vars/junos/variables.yml
      connection: network_cli
      junos_netconf:
      when: ansible_network_os == 'junos'
